# Generated by Django 6.0 on 2025-12-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
