# Generated by Django 6.0 on 2025-12-30 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
